name: Publish .NET 8 Desktop App
on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Cache .NET dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Publish
      run: dotnet publish ./CalculatorAvalonia/CalculatorAvalonia.csproj --configuration Release --runtime ${{ matrix.platform }}-${{ matrix.arch }} --self-contained true --output ./publish

    # Windows-specific steps
    - name: Generate GUIDs
      if: matrix.os == 'windows-latest'
      run: |
        $productGuid = [Guid]::NewGuid().ToString().ToUpper()
        $upgradeGuid = [Guid]::NewGuid().ToString().ToUpper()
        echo "PRODUCT_GUID=$productGuid" >> $env:GITHUB_ENV
        echo "UPGRADE_GUID=$upgradeGuid" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Create WiX source file
      if: matrix.os == 'windows-latest'
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
          <Product Id="${{ env.PRODUCT_GUID }}" Name="CalculatorAvalonia" Language="1033" Version="1.0.0.0" Manufacturer="AnnasVirtual" UpgradeCode="${{ env.UPGRADE_GUID }}">
            <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />
            <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />
            <MediaTemplate EmbedCab="yes" />
            <Feature Id="ProductFeature" Title="CalculatorAvalonia" Level="1">
              <ComponentGroupRef Id="ProductComponents" />
            </Feature>
          </Product>
          <Fragment>
            <Directory Id="TARGETDIR" Name="SourceDir">
              <Directory Id="ProgramFilesFolder">
                <Directory Id="INSTALLFOLDER" Name="CalculatorAvalonia" />
              </Directory>
            </Directory>
          </Fragment>
          <Fragment>
            <ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER">
              <Component Id="ProductComponent" Guid="*">
                <File Source="$(var.PublishDir)\*" KeyPath="yes" />
              </Component>
            </ComponentGroup>
          </Fragment>
        </Wix>' > installer.wxs

    - name: Create MSI (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        $wixPath = "C:\Program Files (x86)\WiX Toolset v3.14\bin"
        $publishDir = Resolve-Path .\publish
        & "$wixPath\heat.exe" dir $publishDir -dr INSTALLFOLDER -cg ProductComponents -gg -sfrag -srd -scom -sreg -out components.wxs
        & "$wixPath\candle.exe" -dPublishDir="$publishDir" installer.wxs components.wxs -out .\
        & "$wixPath\light.exe" -ext WixUIExtension installer.wixobj components.wixobj -out CalculatorAvalonia-${{ matrix.platform }}-${{ matrix.arch }}.msi
      shell: powershell

    # Linux-specific steps
    - name: Create DEB Package (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p ./deb/DEBIAN
        mkdir -p ./deb/usr/local/bin/CalculatorAvalonia
        cp -r ./publish/* ./deb/usr/local/bin/CalculatorAvalonia/
        echo "Package: CalculatorAvalonia
        Version: 1.0
        Section: base
        Priority: optional
        Architecture: amd64
        Maintainer: AnnasVirtual <annasvirtual@gmail.com>
        Description: Avalonia Calculator Application" > ./deb/DEBIAN/control
        dpkg-deb --build ./deb CalculatorAvalonia-${{ matrix.platform }}-${{ matrix.arch }}.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform }}-${{ matrix.arch }}
        path: ./CalculatorAvalonia-${{ matrix.platform }}-${{ matrix.arch }}.${{ matrix.platform == 'win' && 'msi' || 'deb' }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        assets=""
        for file in ./*/*.msi ./*/*.deb; do
          assets="$assets $file"
        done
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --generate-notes \
          $assets