name: Publish .NET 8 Desktop App
on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            arch: x64
          - os: ubuntu-latest
            platform: linux
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Cache .NET dependencies
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Publish
      run: dotnet publish ./CalculatorAvalonia/CalculatorAvalonia.csproj --configuration Release --runtime ${{ matrix.platform }}-${{ matrix.arch }} --self-contained true --output ./publish
    - name: Create portable artifact
      run: |
        if ("${{ matrix.os }}" -eq "windows-latest") {
          Compress-Archive -Path ./publish/* -DestinationPath ./CalculatorAvalonia-portable-${{ matrix.platform }}-${{ matrix.arch }}.zip
        } else {
          zip -r ./CalculatorAvalonia-portable-${{ matrix.platform }}-${{ matrix.arch }}.zip ./publish
        }
      shell: pwsh
    - name: Create NSIS installer (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install nsis -y
        # Create NSIS script (installer.nsi)
        @'
        !include "MUI2.nsh"
        Name "CalculatorAvalonia"
        OutFile "CalculatorAvalonia-installer-${{ matrix.platform }}-${{ matrix.arch }}.exe"
        InstallDir "$PROGRAMFILES64\CalculatorAvalonia"
        !insertmacro MUI_PAGE_DIRECTORY
        !insertmacro MUI_PAGE_INSTFILES
        !insertmacro MUI_LANGUAGE "English"
        Section
          SetOutPath $INSTDIR
          File /r "publish\*.*"
          CreateShortcut "$DESKTOP\CalculatorAvalonia.lnk" "$INSTDIR\CalculatorAvalonia.exe"
          WriteUninstaller "$INSTDIR\Uninstall.exe"
        SectionEnd
        Section "Uninstall"
          Delete "$DESKTOP\CalculatorAvalonia.lnk"
          RMDir /r "$INSTDIR"
        SectionEnd
        '@ | Out-File -Encoding ASCII installer.nsi
        # Build installer
        makensis installer.nsi
      shell: pwsh
    - name: Upload portable artifact
      uses: actions/upload-artifact@v3
      with:
        name: portable-${{ matrix.platform }}-${{ matrix.arch }}
        path: ./CalculatorAvalonia-portable-${{ matrix.platform }}-${{ matrix.arch }}.zip
    - name: Upload installer artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: installer-${{ matrix.platform }}-${{ matrix.arch }}
        path: ./CalculatorAvalonia-installer-${{ matrix.platform }}-${{ matrix.arch }}.exe

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Validate artifacts
      run: |
        for file in ./*/*; do
          if [[ $file == *.zip ]]; then
            if ! unzip -t "$file" > /dev/null; then
              echo "Error: $file is not a valid zip file"
              exit 1
            fi
          elif [[ $file == *.exe ]]; then
            if ! file "$file" | grep -q "executable"; then
              echo "Error: $file is not a valid executable"
              exit 1
            fi
          fi
        done
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        assets=""
        for file in ./*/*; do
          assets="$assets $file"
        done
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --generate-notes \
          $assets